//@ sourceMappingURL=model.map
// Generated by CoffeeScript 1.6.1

/*
  Здесь реализована модель проекта. В частности игрок.
*/


(function() {
  var Player, World;

  Player = (function() {

    function Player(obj, x, y) {
      this.name = obj;
      this.x = x;
      this.y = y;
    }

    Player.prototype.BoundColX = function(posX) {
      if (posX > 1088) {
        return posX - 12;
      }
      if (posX < 0) {
        return posX + 12;
      }
      return posX;
    };

    Player.prototype.BoundColY = function(posY) {
      if (posY > 720) {
        return posY - 8;
      }
      if (posY < 0) {
        return posY + 8;
      }
      return posY;
    };

    return Player;

  })();

  World = (function() {

    World.prototype.players = [];

    World.prototype.names = [];

    World.prototype.addPlayer = function(pl) {
      this.players[pl.name] = pl;
      return this.names.push(pl.name);
    };

    World.prototype.ExistCond = function(pl) {
      var cond;
      cond = false;
      if (this.players[pl.name] === void 0) {
        cond = true;
      }
      return cond;
    };

    function World(obj) {
      switch (typeof obj) {
        case 'object':
          this.players = obj.players;
          this.names = obj.names;
          break;
        default:
          this.players = [];
          this.names = [];
      }
    }

    return World;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = {
      Player: Player,
      World: World
    };
  }

  if (typeof window !== "undefined" && window !== null) {
    window.Player = Player;
  }

  if (typeof window !== "undefined" && window !== null) {
    window.World = World;
  }

}).call(this);
