//@ sourceMappingURL=server.map
// Generated by CoffeeScript 1.6.1

/*
  BEGIN server routine
*/


(function() {
  var app, fs, gamemap, io, model;

  fs = require('fs');

  app = require('http').createServer(function(req, res) {
    var page;
    page = req.url === '/' ? '/index.html' : req.url;
    return fs.readFile(__dirname + page, function(err, data) {
      if (err) {
        res.writeHead(500);
        return res.end("Error loading " + page);
      } else {
        res.writeHead(200);
        return res.end(data);
      }
    });
  });

  io = require('socket.io').listen(app);

  app.listen(8080);

  /*
    END server r outine
  */


  model = require('./js/model.js');

  gamemap = new model.World();

  io.sockets.on('connection', function(socket) {
    socket.on('new user', function(player) {
      if (gamemap.ExistCond(player)) {
        gamemap.addPlayer(player);
        socket.emit('add world', gamemap);
        return socket.broadcast.emit('add user', player);
      }
    });
    return socket.on('update user', function(player) {
      return socket.broadcast.emit('change user', player);
    });
  });

}).call(this);
